apiVersion: v1
kind: Service
metadata:
  name: bonita-service-using-postgresql
  namespace: bonita
spec:
  selector:
    app: bonita
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
